-- Clear existing data to avoid issues with re-running migrations in dev.
TRUNCATE TABLE agents RESTART IDENTITY CASCADE;

-- Seed sample AI agents
INSERT INTO agents (
  name, description, type, industry, status, accuracy_rate, tasks_completed,
  capabilities, max_concurrent_tasks, learning_rate, total_training_hours, skill_points,
  user_id, organization_id, configuration
) VALUES
(
  'Construction Takeoff Assistant',
  'Automates material quantification and cost estimation from construction blueprints, reducing manual effort by up to 90%.',
  'analytical',
  'construction',
  'active',
  0.98,
  1250,
  '{"blueprint_analysis", "material_quantification", "cost_estimation"}',
  5,
  1.2,
  250,
  15000,
  NULL, NULL,
  '{"model": "gpt-4-turbo", "temperature": 0.2}'
),
(
  'Customer Support Bot',
  'Handles customer inquiries via email and chat, providing instant responses and intelligent ticket routing.',
  'conversational',
  'customer-service',
  'active',
  0.95,
  8500,
  '{"email_handling", "chat_support", "ticket_routing", "sentiment_analysis"}',
  20,
  1.0,
  400,
  25000,
  NULL, NULL,
  '{"model": "claude-3-sonnet", "response_persona": "friendly"}'
),
(
  'Financial Compliance Auditor',
  'Monitors transactions and reports for compliance with financial regulations, flagging potential issues in real-time.',
  'analytical',
  'finance',
  'active',
  0.99,
  500,
  '{"transaction_monitoring", "compliance_check", "report_generation"}',
  10,
  1.5,
  320,
  18000,
  NULL, NULL,
  '{"model": "gpt-4o", "strict_mode": true}'
),
(
  'Sales Lead Qualifier',
  'Analyzes incoming leads from various channels to score and qualify them, enriching data and syncing with CRM.',
  'automation',
  'sales',
  'active',
  0.92,
  25000,
  '{"lead_scoring", "data_enrichment", "crm_integration"}',
  15,
  0.9,
  180,
  12000,
  NULL, NULL,
  '{"crm_system": "salesforce", "scoring_model": "v2.1"}'
),
(
  'Healthcare Data Extractor',
  'Extracts and structures patient data from various medical documents, including lab reports and clinical notes.',
  'automation',
  'healthcare',
  'training',
  0.88,
  300,
  '{"ocr", "data_extraction", "hipaa_compliance"}',
  5,
  1.8,
  80,
  5000,
  NULL, NULL,
  '{"document_types": ["pdf", "tiff"], "output_format": "json"}'
),
(
  'Manufacturing QC Inspector',
  'Analyzes product images from the assembly line to detect defects and ensure quality standards are met.',
  'analytical',
  'manufacturing',
  'active',
  0.97,
  150000,
  '{"image_analysis", "defect_detection", "quality_reporting"}',
  50,
  1.1,
  500,
  35000,
  NULL, NULL,
  '{"camera_feed": "rtsp://...", "defect_threshold": 0.95}'
),
(
  'Retail Inventory Manager',
  'Optimizes stock levels by analyzing sales data, predicting demand, and automating reorder processes.',
  'automation',
  'retail',
  'active',
  0.96,
  4500,
  '{"demand_forecasting", "inventory_optimization", "order_automation"}',
  10,
  1.3,
  220,
  14000,
  NULL, NULL,
  '{"reorder_point": 20, "safety_stock_days": 7}'
),
(
  'Project Coordinator Agent',
  'Coordinates tasks between multiple agents, manages complex project workflows, and provides progress reports.',
  'coordinator',
  'other',
  'active',
  0.99,
  200,
  '{"task_delegation", "workflow_management", "progress_tracking"}',
  5,
  1.0,
  150,
  9000,
  NULL, NULL,
  '{"reporting_frequency": "daily"}'
),
(
  'Document Summarizer',
  'Generates concise summaries of long documents, reports, and articles, extracting key phrases and insights.',
  'analytical',
  'other',
  'inactive',
  0.93,
  1200,
  '{"text_summarization", "nlp", "key_phrase_extraction"}',
  10,
  1.0,
  90,
  7000,
  NULL, NULL,
  '{"summary_length": "short"}'
),
(
  'Social Media Content Creator',
  'Generates engaging content for various social media platforms based on trends, brand guidelines, and performance data.',
  'automation',
  'sales',
  'active',
  0.91,
  3200,
  '{"content_generation", "image_creation", "trend_analysis"}',
  10,
  1.2,
  150,
  11000,
  NULL, NULL,
  '{"platforms": ["twitter", "linkedin"], "tone": "professional"}'
);
